### ISSUE TITLE
Update version in 'About'

### ISSUE THREAD

**Issue by gbdomubpkm** [walking-octopus/translate-ut#10]
I just downloaded version 1.2.4 (what's new inside ?)  and version 1.0.0 is still mentioned in 'About'.

![screenshot20220529_143331160](https://user-images.githubusercontent.com/50362604/170868974-ffa36ee6-ee16-462e-8080-10de10821d49.png)

**Comment by walking-octopus** [comment]
Fixed in the last commit.

**Comment by gbdomubpkm** [comment]
Just seen it is not fixed : always shown v  1.0.0 with v 1.2.3
